Autocomplete usage
RechInformatica/rech-editor-cobol pull request #60
Opened 2023-12-20 16:57 UTC by GabrielPdaC

2023-12-20 20:00 UTC, Lucasspaniol requested changes
Very good, just a few adjustments to anticipate use in other COBOL development standards

2023-12-21 13:53 UTC, GabrielPdaC commented on src/lsp/completion/CobolVariable.ts
> +        const decRegExp: RegExp = /^[A-Za-z][A-Za-z0-9_]*-[A-Za-z0-9_-]*$/i;
Adjusted according to your suggestion

2023-12-21 14:00 UTC, GabrielPdaC commented on src/lsp/completion/CobolVariable.ts
> +        const alfaRegExp: RegExp = /x\(\d+\)/i;
Adjusted pic x regex

2023-12-21 19:51 UTC, Lucasspaniol approved these changes
👍

2023-12-21 19:56 UTC, merged